# Title: Mandelbrot Explorer
name = "mandelbrot_explorer"
description = "A hardware-accelerated Mandelbrot renderer"
version = "0.1.0-dev"

authors = ["Marcin Kaim"]
maintainers = ["Marcin Kaim <9829098+marcinkaim@users.noreply.github.com>"]
maintainers-logins = ["marcinkaim"]

[[depends-on]]
gnat = ">=12"
gprbuild = ">=22"
aunit = "^24.0.0"